### ISSUE TITLE
Buster is bust

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/coral-pi-rest-server#13]
As title, appears the coral build scripts haven't been updated for Buster yet. Track progress here. My error:

```
pi@tpu-pi:/usr/local/lib/python3.7/dist-packages/edgetpu/demo $ python3 classify_image.py \
> --model ~/Downloads/mobilenet_v2_1.0_224_inat_bird_quant_edgetpu.tflite \
> --label ~/Downloads/inat_bird_labels.txt \
> --image ~/Downloads/parrot.jpg
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_edgetpu_cpp_wrapper', [dirname(__file__)])
  File "/usr/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_edgetpu_cpp_wrapper'
```

**Comment by robmarkcole** [comment]
Got a reply from google

```
Hello Robin,

Thank you for your interest in Coral. Our team is actively working to fix the compatibility issue between the latest Raspbian and the USB Accelerator, in the meantime please check out this for a temporary fix:  

- "Part II - Methodology" in the link https://blog.hackster.io/benchmarking-machine-learning-on-the-new-raspberry-pi-4-model-b-88db9304ce4 

Thanks
Coral Support Team
```

**Comment by robmarkcole** [comment]
There are now disk images at https://github.com/google-coral/edgetpu-platforms#prebuilt-images-for-raspberry-pis

**Comment by robmarkcole** [comment]
I confirm the google disk image with Buster is functional
