### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by tigroz** [robmarkcole/coral-pi-rest-server#43]
following your guide, i'm trying to run **python3 coral-app.py** but i get this:

`pi@raspberrypi:~/coral-pi-rest-server $ python3 coral-app.py
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "coral-app.py", line 6, in <module>
    from edgetpu.detection.engine import DetectionEngine
  File "/usr/local/lib/python3.5/dist-packages/edgetpu/detection/engine.py", line 17, in <module>
    from edgetpu.basic.basic_engine import BasicEngine
  File "/usr/local/lib/python3.5/dist-packages/edgetpu/basic/basic_engine.py", line 17, in <module>
    from edgetpu.swig.edgetpu_cpp_wrapper import BasicEnginePythonWrapper
  File "/usr/local/lib/python3.5/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 28, in <module>
    _edgetpu_cpp_wrapper = swig_import_helper()
  File "/usr/local/lib/python3.5/dist-packages/edgetpu/swig/edgetpu_cpp_wrapper.py", line 24, in swig_import_helper
    _mod = imp.load_module('_edgetpu_cpp_wrapper', fp, pathname, description)
  File "/usr/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: numpy.core.multiarray failed to import`

i'm on standard Raspbian GNU/Linux 9 (stretch) ( Raspberry 3+)
i've installed  the Edge TPU runtime and Python library from the coral site
any idea?
 
this is my home structure:

```
pi@raspberrypi:~ $ ls
all_models            env               start_assistant.sh
coral-pi-rest-server  googleassistant   Templates
Desktop               Music             tv_grab_italy_basic_url.py
Documents             Pictures          tv_grab_italy_sky_url.py
Downloads             Public            Videos
edgetpu_api           Python-3.6.8
edgetpu_api.tar.gz    Python-3.6.8.tgz
```

**Comment by robmarkcole** [comment]
I recommend you update to raspbian buster or use one of the disk images described in the readme. This is a numpy version incompatability
